### ISSUE TITLE
Can't download fasttext slovenian binaries

### ISSUE THREAD

**Issue by belerico** [anhaidgroup/deepmatcher#17]
Fasttext binaries download does not work unless you select the english language.
Looking at the code i presume that is due to the fact that the english binaries is located at some google drive folder, while the others will be automatically downloaded from an aws server, that it seems unreachable

**Comment by belerico** [comment]
https://github.com/belerico/deepmatcher/tree/torch_1.0.1

**Comment by mustfkeskin** [comment]
How we can change language not english fasttext embeddings

**Comment by belerico** [comment]
Try look at my modified version of deepmatcher here: https://github.com/belerico/deepmatcher/blob/torch_1.0.1/deepmatcher/data/field.py
