### ISSUE TITLE
can't save model state

### ISSUE THREAD

**Issue by walide67** [anhaidgroup/deepmatcher#29]
hello world
please please i need your help the date to presenting my graduation project is nearing
i get error when i tried to save model
my code is :

```
import deepmatcher as dm
import pandas as pd
import numpy as np
import os
train_set,validation_set = dm.data.process(
    path="deepmatcher_model/",
    cache='train_cache.pth',
    train='train.csv',
    validation='valid.csv',
    embeddings='fasttext.fr.bin',
    embeddings_cache_path="deepmatcher_model/",
    ignore_columns=['id','','ltable_index','rtable_index'],
    id_attr='_id', 
    label_attr='label',
    left_prefix='ltable_', 
    right_prefix='rtable_')
model=dm.MatchingModel(attr_summarizer='hybrid')
model.initialize(train_set)
model.run_train(
    train_dataset=train_set,
    validation_dataset=validation_set,
    epochs=20,
    batch_size=16,
    best_save_path='deepmatcher_model/hybrid_model.pth',
    pos_neg_ratio=3)
model.save_state('hybrid_model.pth',include_meta=True)
```
the error message :

> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 model.save_state('hybrid_model.pth',include_meta=True)
> 
> 4 frames
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in _save(obj, f, pickle_module, pickle_protocol)
> 196 pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
> 197 pickler.persistent_id = persistent_id
> --> 198 pickler.dump(obj)
> 199
> 200 serialized_storage_keys = sorted(serialized_storages.keys())
> 
> AttributeError: Can't pickle local object 'MatchingDataset.finalize_metadata..'

please tell me how can i solve this
i use google colab ..
thanks .. and i am sorry for my english
@thodrek @sidharthms @hanli91 @anhaidgroup

**Comment by sidharthms** [comment]
You can modify `save_state` to use dill for pickling:

```
import deepmatcher as dm
import pandas as pd
import numpy as np
import os
import torch
import dill

train_set,validation_set = dm.data.process(
    path="deepmatcher_model/",
    cache='train_cache.pth',
    train='train.csv',
    validation='valid.csv',
    embeddings='fasttext.fr.bin',
    embeddings_cache_path="deepmatcher_model/",
    ignore_columns=['id','','ltable_index','rtable_index'],
    id_attr='_id', 
    label_attr='label',
    left_prefix='ltable_', 
    right_prefix='rtable_')
model=dm.MatchingModel(attr_summarizer='hybrid')
model.initialize(train_set)
model.run_train(
    train_dataset=train_set,
    validation_dataset=validation_set,
    epochs=20,
    batch_size=16,
    best_save_path='deepmatcher_model/hybrid_model.pth',
    pos_neg_ratio=3)

def save_state(self, path, include_meta=True):
    """ Copied from https://github.com/anhaidgroup/deepmatcher/blob/master/deepmatcher/models/core.py
    """
    state = {'model': self.state_dict()}
    for k in self._train_buffers:
        if include_meta or k != 'state_meta':
            state[k] = getattr(self, k)
    torch.save(state, path, pickle_module=dill)  # specify dill as pickling module
save_state(model, 'hybrid_model.pth',include_meta=True)
```

**Comment by walide67** [comment]
thanks @sidharthms  for your reply
i get the same error  :(

> AttributeError                            Traceback (most recent call last)
> <ipython-input-15-0056771f4947> in <module>()
> ----> 1 model.save_state('hybrid_model2.pth',include_meta=True)
> 
> 4 frames
> /usr/local/lib/python3.6/dist-packages/deepmatcher/models/core.py in save_state(self, path, include_meta)
>     459             if include_meta or k != 'state_meta':
>     460                 state[k] = getattr(self, k)
> --> 461         torch.save(state, path)
>     462 
>     463     def load_state(self, path):
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol)
>     133         pickle_protocol: can be specified to override the default protocol
>     134     """
> --> 135     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
>     136 
>     137 
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in _with_file_like(f, mode, body)
>     115         f = open(f, mode)
>     116     try:
> --> 117         return body(f)
>     118     finally:
>     119         if new_fd:
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in <lambda>(f)
>     133         pickle_protocol: can be specified to override the default protocol
>     134     """
> --> 135     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
>     136 
>     137 
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in _save(obj, f, pickle_module, pickle_protocol)
>     196     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
>     197     pickler.persistent_id = persistent_id
> --> 198     pickler.dump(obj)
>     199 
>     200     serialized_storage_keys = sorted(serialized_storages.keys())
> 
> AttributeError: Can't pickle local object 'MatchingDataset.finalize_metadata.<locals>.<lambda>'

@thodrek @hanli91 @anhaidgroup

**Comment by walide67** [comment]
it's work 
I am very grateful to you @sidharthms 
thank you bro

**Comment by sidharthms** [comment]
This is now fixed on master.
