### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by TianyiDuan** [anhaidgroup/deepmatcher#37]
import deepmatcher as dm
import torch

torch.cuda.is_available()
import pandas as pd
pd.read_csv(r'E:\project\deepmatcher\examples\sample_data\itunes-amazon\train.csv').head()

train, validation, test = dm.data.process(
    path='E:\project\deepmatcher\examples\sample_data\itunes-amazon',train='train.csv', validation='validation.csv',test='test.csv')
model = dm.MatchingModel()

Windows system
How to deal with this problem？

**Comment by TianyiDuan** [comment]
find util.py
  #csv.field_size_limit(sys.maxsize)
then you can solve this problem

**Comment by sidharthms** [comment]
I assume this is fixed, please reopen if you still have issues.
