### ISSUE TITLE
Error: Expected object of backend CPU but got backend CUDA for argument #3 'index'

### ISSUE THREAD

**Issue by Dingyue96** [anhaidgroup/deepmatcher#46]
when run the code with dataprocess
`train, validation, test = dm.data.process(
    path='sample_data/itunes-amazon',
    train='train.csv',
    validation='validation.csv',
    test='test.csv')`
I got the error with " **Expected object of backend CPU but got backend CUDA for argument #3 'index**'"
here my device is support cuda, while torch.cuda.is_avaliable() is true and torch.device('cuda:0' if torch.cuda.is_available() else 'cpu') get the value of device(type='cuda', index=0).

how can i  fix this problem? hope for solution.

**Comment by sidharthms** [comment]
This should be fixed on master, will update PyPi soon. Please reopen the issue if this persists.
