### ISSUE TITLE
Data links dead

### ISSUE THREAD

**Issue by mjudell** [anhaidgroup/deepmatcher#47]
It looks like the links on the data page, and the ref to the paper are dead https://github.com/anhaidgroup/deepmatcher/blob/master/Datasets.md

**Comment by sidharthms** [comment]
I just tried it now, it seems to be working - could you retry and let me
know? If there is an error message, please paste it here.

**Comment by mjudell** [comment]
If you are using a DNS inside wisc.edu, you may be getting a local mirror?

https://pages.cs.wisc.edu/~anhai/data1/deepmatcher_data/Structured.zip

Returns: 
Sorry! The URL you requested was not found on our server.
Is it Sunday between 4 and 8 PM (CST)?
If so, the server may be undergoing regularly scheduled downtime.
Otherwise, please contact the maintainer of the referring page and ask them to fix their link.
Thanks!

**Comment by sidharthms** [comment]
For some reason you seem to have got an https link, try this:
http://pages.cs.wisc.edu/~anhai/data1/deepmatcher_data/Structured.zip

**Comment by mjudell** [comment]
Worked like a charm.  Many thanks!
