### ISSUE TITLE
Why use mask_fill_ ?

### ISSUE THREAD

**Issue by fukien** [anhaidgroup/deepmatcher#50]
Hi, I have just read your codes. 
I found that in many scripts you use  'masked_fill_' for tensor computation, eg.,
    word_aggregators.py:139-140
    word_comparators.py:173-175
    word_contexualizers.py:157-159

Could you please tell me why you use masked_fill for tensors?

**Comment by sidharthms** [comment]
We perform attention over a batch of word sequences each with different lengths. In this case, we want to ensure that the padding tokens that are beyond the end of sequence get 0 attention weights. Masked fill is used to effectively set the attention scores to zero for those tokens.

**Comment by sidharthms** [comment]
Please re-open if you have questions.
