### ISSUE TITLE
Cannot achieve the precision/recall/F1 reported in SIGMOD18

### ISSUE THREAD

**Issue by EliasMei** [anhaidgroup/deepmatcher#51]
Hi, I have just tested deepmatcher on the walmart-amazon dataset.
However, I cannot achieve the precision/recall/F1 reported in SIGMOD18.

```
import deepmatcher as dm
import logging
import torch

logging.getLogger('deepmatcher.core').setLevel(logging.INFO)

model = dm.MatchingModel(attr_summarizer=dm.attr_summarizers.RNN(word_aggregator='birnn-last-pool'))
# model = dm.MatchingModel()
print(model)
model.initialize(train_dataset)  # Explicitly initialize model.

model = model.cuda()
lr_decay = [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
batch_size = [16, 32]
pos_neg_ratio = [10, 7, 5, 4, 3, 2, 1]

best_f1 = -1
best_params = {'lr_decay': -1, 'batch_size': -1, 'pos_neg_ratio':-1}
for alpha in lr_decay:
    for b in batch_size:
        for rho in pos_neg_ratio:
            optimizer = dm.optim.Optimizer(lr_decay=alpha)
            model.run_train(
                train_dataset,
                validation_dataset,
                epochs=15,
                batch_size = b,
                pos_neg_ratio=rho,
                optimizer=optimizer,
                best_save_path='../output/walmart-amazon/rnn_model.pth')
            print(f'lr_decay: {alpha}, batch_size:{b}, pos_neg_ratio:{rho}')
            f1 = model.run_eval(test_dataset)
            if f1 > best_f1:
                best_f1 = f1
                best_params['lr_decay'] = alpha
                best_params['batch_size'] = b
                best_params['pos_neg_ratio'] = rho
                print(f'best f1-score: {best_f1}, {best_params}')
print(f'best f1-score: {best_f1}, {best_params}')
```

I haven't yet tested all the hyperparameters, but the available results show that f1-score is only about 37%.
However, the f1 reported in SIGMOD18 is 67.6% for RNN on the structured walmart-amazon dataset.
I use the data downloaded from the link in this repository.

Could you tell me what the problem is？ 
What are the hyper-parameters selected for the experiments in SIGMOD 18 (RNN)?

**Comment by sidharthms** [comment]
Hi, I tried re-running the training for walmart amazon with the RNN model and am able to get the same/better results. The code and results is in this colab: https://colab.research.google.com/drive/14oacgxGheumvekKUq_VpLqOMzEFbIAVM#scrollTo=lejVqpjAQJPD

**Comment by sidharthms** [comment]
Please re-open if you have any questions.

**Comment by sidharthms** [comment]
This is a similar example for reproducing the result of the "dirty" variant of DBLP-ACM: https://colab.research.google.com/drive/1O372fS80m7SB38DRu9WRFu6pARVtkEOr#scrollTo=Dv_sFh1_QJOs
