### ISSUE TITLE
Where are embeddings generated during processing stored?

### ISSUE THREAD

**Issue by jweckschmied** [anhaidgroup/deepmatcher#65]
Hi, how would I go about viewing (and potentially modifying) the actual embedding vectors that are generated by `dm.data.process` ? I'm having a hard time figuring out where they are located.

**Comment by sidharthms** [comment]
~/.vector_cache by default: https://github.com/anhaidgroup/deepmatcher/blob/master/deepmatcher/data/process.py#L98
