### ISSUE TITLE
How is F1 calculated (micro, macro, weighted)?

### ISSUE THREAD

**Issue by ziqizhang** [anhaidgroup/deepmatcher#73]
Hi

Could you please confirm that when the following method is run:

`model.run_eval(test)`

Is the PRF1 score calculated using micro-averaging, or macro, or weighted-macro?

Thanks

**Comment by zhouhuhq** [comment]
+1 I have the same question

**Comment by sidharthms** [comment]
Deepmatcher operates in a binary classification setting - it classified whether an input pair is a match or not. It's not a multi-class scenario, so micro & macro averaging are not relevant. You can the fine details of F1 computation in the implementation of this class: https://github.com/anhaidgroup/deepmatcher/blob/26fd49270b06e943ba1302753757a48928337342/deepmatcher/runner.py#L27

Please re-open the bug if this does not answer your question.
