### ISSUE TITLE
AttributeError: module 'torchtext.data' has no attribute 'Field'

### ISSUE THREAD

**Issue by nilbahaaeddine** [anhaidgroup/deepmatcher#80]
I am trying to import deepmatcher using:

import deepmatcher as dm

and I am getting the following error message:

AttributeError: module 'torchtext.data' has no attribute 'Field'

**Comment by sidharthms** [comment]
This should now be fixed with the latest version on PyPI. Please run `pip install --upgrade --force-reinstall deepmatcher` and try again.
